### PR TITLE
Add view shortcut

### LINKED ISSUE #592: Easier way to set status code
Right now, we set the status code by `request.status_code(###)` in the controller. This does feel clunky. The more I think about it, the more I really think we should implement something like 
```return view('page.html'), 201```. 

Doing,

```
`request.status_code(###)` 

return view('blah')
```

is very cumbersome.

We can also set it in the `view` method. Either way, I think this change could really help devs out. It is just simple.

### PR DESCRIPTION
**Pull request by josephmancuso**
Closes #592 

This PR allows you to set a status codes easier. You can now do something like this when returning a view.

we currently do something like this:

```python
def show(self, view: View, request: Request):
    request.status(203)
    return view.render('some.view', {'key': 'value'})
```

now you can do:

```python
def show(self, view: View):
    return view.render('some.view', {'key': 'value'}) & 203
```

the `&` is a shortcut is still experimental and could change. Any suggestions are welcome.

### CODE REVIEW

**Comment by hammacktony** [comment]
Can we also set the status? Like `return view(##) & '404 Not Found'`. There are probably some that would like that.

**Comment by Marlysson** [comment]
Why not a third argument like:

view.render(template, data, status)

**Comment by josephmancuso** [comment]
@Marlysson thats a fair argument. we could deff do that. Would prob make more sense honestly.

**Comment by hammacktony** [comment]
What if you were returning something else than a view?

**Comment by hammacktony** [comment]
I also think that `View` objects should not mess with `Request` objects. There should be some separation. These two objects meet in the controller. So, this is where this should be implemented.

**Comment by josephmancuso** [comment]
the more i think about this, the more i'm not really a fan .. Not sure if this is the way to accomplish what we are trying to do ..

**Pull request closed without merging**
