### PR TITLE
test coverage setup for deepsource

### PR DESCRIPTION
**Pull request by vaibhavmule**

### CODE REVIEW

**Comment by josephmancuso** [comment]
is there a way to ignore some of these errors we don't need to worry about?

**Comment by josephmancuso** [comment]
first one for example: https://github.com/MasoniteFramework/core/pull/576/checks?check_run_id=129155390

**Comment by vaibhavmule** [comment]
I am not sure, I am tagging @sanketsaurav.

**Comment by vaibhavmule** [comment]
Also, I am not sure why I am getting following error. 
```
DeepSource | Error | Reporting failed |  Analyzer 'test-coverage' not activated for '[secure]Framework/core'
```

**Comment by sanketsaurav** [comment]
> first one for example: https://github.com/MasoniteFramework/core/pull/576/checks?check_run_id=129155390

Hey @josephmancuso! We're adding the ability to ignore an issue for a file or a file pattern in an upcoming release (this weekend). You would be able to do that right from the DeepSource UI. I'll update here once that's out :)

**Comment by sanketsaurav** [comment]
@vaibhavmule You need to enable the `test-coverage` analyzer in your `.deepsource.toml` file to start using Test Coverage tracking. You can find the docs here --> https://deepsource.io/docs/analyzers/test-coverage.html

**Comment by vaibhavmule** [comment]
@sanketsaurav You can check this PR, I have enabled that.

**Comment by sanketsaurav** [comment]
@vaibhavmule Yes, this looks good. Once this has been merged to your default branch, you can start tracking test coverage.

**Comment by vaibhavmule** [comment]
Note: This has to be merged with 2.1 and then 2.1 to develop branch to take this in effect.

**Pull request merged**
