### PR TITLE
Added route views

### LINKED ISSUE #294: View Routes
It would be useful to provide this functionality 🤔 :

https://laravel.com/docs/5.6/routing#view-routes

### PR DESCRIPTION
**Pull request by josephmancuso**
This PR adds route views. We can use them like this:

```python
ROUTES = [
    Get().view('/url/to/something', 'template/location', {'key': 'value'})
]
```

This will simply return the template instead of needing a controller at all

Closes #294

### CODE REVIEW

**Comment by josephmancuso** [comment]
I also removed all the flag pole comments because it was messing up the reference docs when generating those

**Comment by josephmancuso** [comment]
affect the code how so? in terms of being similiar?

**Comment by clsource** [comment]
Not affect the code since they are just comments. But the docs. Are there other places that flagpole could damage rendering the docs?. Idk I just though about that.

**Comment by josephmancuso** [comment]
oh ummm . I used to be a fan of flagpole comments but my thoughts have changed overtime lol. I think the only place I put them were in service providers and in the `/masonite` repo itself

**Comment by clsource** [comment]
It has nothing to do with this pull request though. Just maybe look for another files that may need to ditch that comment style

**Comment by clsource** [comment]
It has nothing to do with this pull request though. Just maybe look for another files that may need to ditch that comment style

**Pull request merged**
