### PR TITLE
directly returning a Paginator or LengthAwarePaginator instance

### PR DESCRIPTION
**Pull request by garyburgmann**
directly returning a Paginator or LengthAwarePaginator instance from a controller now creates a JSON response. The JSON response includes the collection data as well as the meta data regarding paginated collection.

### CODE REVIEW

**Comment by garyburgmann** [comment]
Have also made a pull req. into docs, and nested the info in the basics/controllers section

**Comment by josephmancuso** [comment]
This is perfect. Can you just add a simple test somewhere to assert that the returned JSON has a few paginated results? This way we can track if it breaks in the future.

**Comment by garyburgmann** [comment]
Will do. Under the pump at the moment, but hopefully will find an opportunity in the next 48 hours

**Comment by garyburgmann** [comment]
tests written for this now @josephmancuso

**Comment by josephmancuso** [comment]
i merged this into master instead of 2.2 4b7c4c9685a6b65afc28d4ff30619ba2080640b3

**Pull request closed without merging**
