### PR TITLE
Remove the redundant coveralls reporting

### LINKED ISSUE #291: Remove the redundant coveralls reporting on every single python version
You may have noticed that coveralls comments like 3 or 4 times on a pull request reporting the coverage. This is because it is set to report on every successful build in the travis.yml file. We need to pick 1 python version and only report for that

### PR DESCRIPTION
**Pull request by vaibhavmule**
Closes #291

### CODE REVIEW

**Comment by vaibhavmule** [comment]
@coveralls Why is it showing coverage:unknown and not showing percentage?

**Comment by josephmancuso** [comment]
Hm looks like the coverage ran but it didn’t return a percentage?

**Comment by vaibhavmule** [comment]
@josephmancuso it may be because this commit does not require any coverage and we had omitted `.travis.yml` in https://github.com/MasoniteFramework/core/blob/master/.coveragerc

**Comment by josephmancuso** [comment]
i'll merge this in and hope it works 🤞

**Comment by vaibhavmule** [comment]
Got a reply, let me write it again and check if it works. 
https://github.com/lemurheavy/coveralls-public/issues/1185#issuecomment-420083282

**Pull request merged**
