### PR TITLE
Redis Cache Driver

### PR DESCRIPTION
**Pull request by mitchdennett**
This PR is for implementing Redis as a Cache Driver. There are some (a lot more) configuration settings we could allow the user to set. Not sure how many we want to add straight away or just see how this works and add them as people request them?

### CODE REVIEW

**Comment by josephmancuso** [comment]
This is awesome!

**Comment by josephmancuso** [comment]
Just had to make a slight modification to the tests. Now only the test runs when the `REDIS_CACHE_DRIVER` environment variable is true. This way I can run the tests on my or your computer when we need to instead of needing a Redis server every time we run tests or needing to set one up for Travis

**Comment by josephmancuso** [comment]
Might be worth looking at how I modified the tests though: https://github.com/MasoniteFramework/core/blob/master/tests/test_cache.py#L25-L30

**Comment by mitchdennett** [comment]
Good catch about the tests. I didn't think about that.

**Pull request merged**
