### PR TITLE
added auth dir in AuthCommand to move controllers to controllers/auth/

### PR DESCRIPTION
**Pull request by vaibhavmule**

### CODE REVIEW

**Comment by gdhameeja** [comment]
Didn't receive a comment on this PR until now. Do I need to update anything?

**Comment by josephmancuso** [comment]
A quick look shows that you also need to update this block too to point the controllers to the new subdirectory https://github.com/MasoniteFramework/core/blob/2.2/masonite/commands/AuthCommand.py#L21-L35

**Comment by gdhameeja** [comment]
@josephmancuso  Made the change in routers as well.

**Comment by gdhameeja** [comment]
Hey, awaiting review.

**Comment by josephmancuso** [comment]
@vaibhavmule ☝️ can you review this? This will need a manual review at the moment

**Comment by josephmancuso** [comment]
Since this is a directory change I'd like to move this into the develop branch

**Pull request merged**
