### PR TITLE
Improvements requirements.txt

### PR DESCRIPTION
**Pull request by mapeveri**
I had some problems getting everything. This is my solution.

### CODE REVIEW

**Comment by josephmancuso** [comment]
what does this solve? The only thing in requirements.txt should really be only dependencies for development if there are any.

when testing you should do (preferably inside your virtual environment):

    $ pip install .

which installs everything what would have installed when downloading the actual package. 

or am I missing something?

**Comment by mapeveri** [comment]
I always run pip install -r requirements.txt for develop, In addition there are dependencies that are not in setup.py. We would have to find a way to unify it.

**Comment by josephmancuso** [comment]
If you want to unify it you could create a make command for it

**Comment by mapeveri** [comment]
Make command? I thought to do the following:

Create 3 file requirements. 

1. requirements.txt
2. requirements-test.txt
3. requirements-dev.txt

And in the setup.py read the content of requirements.txt

What do you think?

**Comment by josephmancuso** [comment]
Umm not really a fan. What are some dependencies that are not used in the core package itself. Are there any libraries that are only for development? The solution for this should just be to run `pip install .` which will install all the required packages

**Comment by josephmancuso** [comment]
Just do:

`pip install .`
`pip install -r requirements.txt`

Requirements.txt just needs the ably, pusher, boto3 and coveralls packages

**Comment by mapeveri** [comment]
And now  @josephmancuso what do you think?

**Comment by josephmancuso** [comment]
how does the install.sh work?

**Comment by mapeveri** [comment]
Simplely run this together:

```
pip install .
pip install -r requirements.txt
```

For executed run:

`sh install.sh`

**Comment by josephmancuso** [comment]
hmm I'm sorry. After some thinking I just feel like adding a file to run a test just to combine two commands seems silly to me. This will only be useful when someone adds a package to the repo which really won't be that often.

**Comment by mapeveri** [comment]
It is not only to unify two commands. It is also for:

1. Remove dependencies from requirements.txt and leave only those in setup.py
2. Remove duplicate dependencies in setup.py
3. In requirements.txt leave only the 'dev' and 'tests' dependency.

**Pull request closed without merging**
