### PR TITLE
Added route resources Feature/404

### LINKED ISSUE #404: Resourceful route to a controller
```
from masonite.helpers.routes import resource

...
resource('tasks', 'TaskController'), 
...
```
🤔 
[Laravel Resource Controller](https://laravel.com/docs/5.7/controllers#resource-controllers)

### PR DESCRIPTION
**Pull request by josephmancuso**
Can use this:

```python
from masonite.routes import Resource

ROUTES = [
    Resource('/base', 'UserController')
]
```

Can also add names:

```python
ROUTES = [
    Resource('/base', 'UserController', names={
        'create': 'base.build'
    })
]
```

and define only a certain number of routes:

```python
from masonite.routes import Resource

ROUTES = [
    Resource('/base', 'UserController', only=['create', 'index', 'show'])
]
```

This will generate several routes and maps to the routes found here: #404

Closes #404

### CODE REVIEW

**Comment by nioperas06** [comment]
This is not available in 2.3.

**Comment by josephmancuso** [comment]
The feature is just missing?

**Comment by nioperas06** [comment]
Yes.

**Comment by josephmancuso** [comment]
maybe its because the branch is called 404 🤣

**Comment by josephmancuso** [comment]
possible anything staged in master at the time never got merged to 2.3

**Comment by josephmancuso** [comment]
oooh i see why. This is core repo. I need to get this over to Masonite repo. I'll make this priority

**Comment by nioperas06** [comment]
Thank you

**Pull request merged**
