### PR TITLE
Integrate masonite-events into core

### PR DESCRIPTION
**Pull request by rickwest**
References #370. Have added the provider to providers list as per docs. Do I also need to add masonite-events as a requirement in setup.py. Forgive my ignorance, I'm not very familiar with dependancy management in Python.

### CODE REVIEW

**Comment by josephmancuso** [comment]
Yes

**Comment by vaibhavmule** [comment]
@rickwest Do not worry about Travis build is failing, 

I can see that https://github.com/MasoniteFramework/events/releases/tag/v1.0.1 is not released on [pypi](https://pypi.org/project/masonite-events/#history).

This should merge after, https://github.com/MasoniteFramework/core/issues/387

**Comment by rickwest** [comment]
@vaibhavmule Thank you 🙂

**Comment by josephmancuso** [comment]
fixed #387 and rerunning tests

**Comment by josephmancuso** [comment]
@clsource the problem I have with merging things is that although we are going to be using it in core pretty extensively, I can foresee Masonite Events as being much bigger than it currently is which will really bloat core. I'd like core to be ... core ... and then we sort of develop packages and even other developers develop packages and then we can just depend on them.

I just don't want to bloat core with a crap ton of packages. It might be small now but it could get massive once we start thinking of useful features

**Pull request merged**
