### PR TITLE
Add Python 3.7 to .travis.yml

### PR DESCRIPTION
**Pull request by bjorntheart**
Attempt to fix issue #272

### CODE REVIEW

**Comment by bjorntheart** [comment]
Latest fix comes from recommendations upstream [#9815](https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-401756442)

**Comment by bjorntheart** [comment]
`3.4` builds are failing now 👎

**Comment by josephmancuso** [comment]
🤔 hmm let me try to restart that. Travis says it can't find 3.4

**Comment by bjorntheart** [comment]
@josephmancuso Gah! I forgot to remove these global settings
```yaml
...
dist: xenial
sudo: true
...
```

I relocated them here

```yaml
...
python:
- '3.4'
- '3.5'
- '3.6'

matrix:
  include:
    - python 3.7
      dist: xenial
      sudo: true
...
```
This way `dist` and `sudo` aren't globally set which likely broke the `3.4` build

**Comment by josephmancuso** [comment]
https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-401794914

**Comment by bjorntheart** [comment]
That comment refers to this https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-401756442 configuration which is set globally in the travis file. 

6a6c87d8eeccb48c37971c61f5983b3a40d6c68e removes the global definition which broke the `3.4` build and 647a5b4b88c4d06fd1bd8dedbc124d72d5d5466d puts the `3.7` configuration in the `matrix` configuration, where it should be. 

Hope all this is making sense :-)

**Comment by josephmancuso** [comment]
no it deff makes sense lol but it's still failing 🤔

**Comment by bjorntheart** [comment]
Dang! ok. I'll keep searching for answers

**Comment by josephmancuso** [comment]
that's so bizarre that adding that for python 3.7 breaks 3.4 but not 3.5 or 3.6 😠

**Comment by bjorntheart** [comment]
@josephmancuso I had the suspicion that Travis never triggered a build again. Is there a way to manually trigger a build?

**Comment by josephmancuso** [comment]
not on a PR .. possibly make another commit with a blank space or something and see if Travis reads it.

**Comment by josephmancuso** [comment]
that actually makes sense that travis never triggered the build because the travis file shouldn't break 3.4 with that `yml` file that is in this PR lol

**Pull request closed without merging**
