### PR TITLE
Added Python 3.7 support to .travis.yaml

### PR DESCRIPTION
**Pull request by bjorntheart**
#272

### CODE REVIEW

**Comment by bjorntheart** [comment]
@josephmancuso I closed the former PR and reopened a new one and the build still does not trigger. I'm out of ideas :(

**Comment by bjorntheart** [comment]
Oh, great! I forgot a `:` in the yaml file

**Comment by bjorntheart** [comment]
@josephmancuso should `.travis.yml` be excluded from Coveralls checks in `.coveragerc`?

**Comment by josephmancuso** [comment]
Probably. No reason to cover it

**Comment by bjorntheart** [comment]
Cool. Made a PR to omit `travis.yml`

**Pull request merged**
