### PR TITLE
added compact helper

### PR DESCRIPTION
**Pull request by josephmancuso**
it is very repetitive when you want to have a variable name and you want to send a variable to the view with the same name. This may look something like this:

```python
def show(self, view: View):
    posts = Post.all()
    users = User.all()
    return view.render('some.template', {'posts': posts, 'users': users})
```

now you can do:

```python
from masonite.helpers import compact

def show(self, view: View):
    posts = Post.all()
    users = User.all()
    return view.render('some.template', compact(posts, users))
```

You can also pass in a dictionary which will update accordingly:

```python
from masonite.helpers import compact

def show(self, view: View):
    posts = Post.all()
    users = User.all()
    user_blogs = Blog.where('user_id', 1).get()
    return view.render('some.template', compact(posts, users, {'blogs': user_blogs}))
```

### CODE REVIEW

**Comment by vaibhavmule** [comment]
Do you mean?
posts and users without stirng?
`return view.render('some.template', compact(posts, users))`

**Comment by josephmancuso** [comment]
#602

**Comment by nioperas06** [comment]
Is this available in `2.1.19`?

**Comment by josephmancuso** [comment]
no it will be in 2.1.20. I can release now if you like :)

**Comment by nioperas06** [comment]
🙌

**Comment by josephmancuso** [comment]
released

**Pull request merged**
