### PR TITLE
S3 Storage Driver

### PR DESCRIPTION
**Pull request by arpitgogia**
A very simple and basic implementation of an S3 Storage Driver.
Here's the [API reference](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#id200)

@josephmancuso I have only implemented methods that are pretty straight forward to wrap around for now. Methods like `append` and `move` do not seem to have direct APIs. Happy to discuss the implementation strategy for the same. 

Certain methods (e.g. `put` and `upload`) seem redundant in this case, can be handled by raising a `NotImplementedException` and directing to the corresponding implemented method.

### CODE REVIEW

**Comment by vaibhavmule** [comment]
Can you tell me what are you trying to implement here?

**Comment by josephmancuso** [comment]
He’s implementing an S3 version of the disk storage driver. I’d like to create these wrappers around managing files and created one for disks he is going to create one for the S3 driver

**Comment by josephmancuso** [comment]
not sure whats going on with this but i don't see any files changes 🤔 . I also can't find the class you made. It looks like the last commit deleted the class

**Comment by arpitgogia** [comment]
@josephmancuso sorry, I missed your comment above about the file getting deleted. What’s the solution for this? I still have the file locally because I haven’t pulled.

**Comment by josephmancuso** [comment]
not sure how the file was deleted but it's possible that a simple `git reset <commit>` . can get you back to where you were before the file was deleted.

**Comment by arpitgogia** [comment]
@josephmancuso I think it's there now

**Pull request closed without merging**
