### PR TITLE
Sign related view helpers ADDED

### PR DESCRIPTION
**Pull request by danieldsf**
I just created a new file that exposes the sing related functions like sign, unsign, encrypt and decrypt.

### CODE REVIEW

**Comment by danieldsf** [comment]
Sounds good. I will change the code to be like that! Thank you for your patience!

**Comment by danieldsf** [comment]
I removed the tests that I have implemented by mistake but it seems the warnings are affecting the build.

**Comment by danieldsf** [comment]
I am gonna work a bit more on this one.

**Comment by danieldsf** [comment]
I am going to close this one and start a brand new PR with more methods.

**Comment by josephmancuso** [comment]
Awesome sounds good 👍

**Comment by josephmancuso** [comment]
@danieldsf the tests are failing because of flake8 issues. We use pep8 coding standards which flake8 validates. You can find the issues on the bottom here: https://travis-ci.org/MasoniteFramework/core/jobs/514156451#L984-L991

If you use VSCode or other text editors with extensions then you can usually install a python extension, right click and do "Format Document". That's what i do.

**Pull request closed without merging**
