### PR TITLE
Refactor the core library to use poetry

### PR DESCRIPTION
**Pull request by aisola**
Yeah, so this should work. Everything on my end worked. :smile:

Using poetry will give us much better ability to ensure that versions are correct for the core framework.

### CODE REVIEW

**Comment by aisola** [comment]
Sooo.... This failed because of the CI's configuration. @josephmancuso How should we deal with this case?

**Comment by josephmancuso** [comment]
just change the travis.yml file

**Comment by josephmancuso** [comment]
just make it use poetry instead of pip

**Comment by aisola** [comment]
Ha. Duh. I feel like an idiot. I'll make the change.

**Comment by aisola** [comment]
Okay.

So one of the sass tests fail, I can't tell if that is a version thing or if it is something else. Have you seen this issue before @josephmancuso?

Also, the upload tests fail because of boto3. Though the way I've put this together, the boto3 library _should_ be installing, but it is obviously not for some reason. I'll take another look at this later and see if I can figure it out more.

**Comment by josephmancuso** [comment]
Looks like its not correctly installing any extras

**Comment by aisola** [comment]
I knew it wasn't installing some of them for sure. I couldn't quite tell if the CI wasn't installing _any_ of them. I'll look into it more.

**Comment by josephmancuso** [comment]
75.22s$ poetry install -E sass -E s3 -E scheduler -E entry

Installing dependencies from lock file
Package operations: 39 installs, 3 updates, 0 removals
  - Installing argh (0.26.2)
  - Installing asn1crypto (0.24.0)
  - Installing atomicwrites (1.1.5)
  - Installing attrs (18.1.0)
  - Installing backpack (0.1)
  - Installing bcrypt (3.1.4)
  - Installing blinker (1.4)
  - Installing cffi (1.11.5)
  - Installing cryptography (2.2.2)
  - Installing faker (0.7.18)
  - Installing inflection (0.3.1)
  - Installing jinja2 (2.10)
  - Installing lazy-object-proxy (1.3.1)
  - Installing markupsafe (1.0)
  - Installing more-itertools (4.2.0)
  - Installing orator (0.9.7)
  - Installing passlib (1.7.1)
  - Installing pathtools (0.1.2)
  - Installing pendulum (1.5.1)
  - Installing pluggy (0.6.0)
  - Updating py (1.4.33 -> 1.5.3)
  - Installing pyaml (16.12.2)
  - Installing pycparser (2.18)
  - Installing pygments (2.2.0)
  - Updating pytest (3.0.7 -> 3.6.1)
  - Installing python-dateutil (2.7.3)
  - Installing python-dotenv (0.8.2)
  - Installing pytz (2018.4)
  - Installing pytzdata (2018.5)
  - Installing pyyaml (3.12)
  - Installing requests-file (1.4.3)
  - Installing setuptools (39.2.0)
  - Installing simplejson (3.15.0)
  - Updating six (1.10.0 -> 1.11.0)
  - Installing tabulate (0.8.2)
  - Installing tldextract (2.2.0)
  - Installing tzlocal (1.5.1)
  - Installing validator.py (1.2.5)
  - Installing waitress (1.1.0)
  - Installing watchdog (0.8.3)
  - Installing whitenoise (3.3.1)
  - Installing wrapt (1.10.11)
install.2

3.97s$ poetry develop
Installing dependencies from lock file
Package operations: 1 install, 0 updates, 0 removals
  - Installing setuptools (39.2.0)
Installing masonite (2.0.4)

**Comment by josephmancuso** [comment]
looks like they are not even pulling in. prob not a CI issue.

**Comment by aisola** [comment]
Closing as stale, pending discussions in other issues.

**Pull request closed without merging**
