### PR TITLE
Update Orator

### PR DESCRIPTION
**Pull request by hammacktony**
Updated `orator` to 0.9.8. Vast bug improvements that can benefit uses.

### CODE REVIEW

**Comment by hammacktony** [comment]
If you check the error log for this PR, Python 3.4 raises an interesting error. It is the classic chicken and the egg scenario. Beta 2.1 requires `orator==0.9.7`, but that is what I am working on at the moment. 

The 2.1 branch needs to be updated first. 

Otherwise, this PR is ready to go. It works for 3.5, 3.6, and 3.7. 3.4 is being stubborn.

**Comment by josephmancuso** [comment]
that is super bizarre 🤔

**Comment by hammacktony** [comment]
I did the `>=0.9.7`. For most systems, it will default to `0.9.8`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hammacktony** [comment]
Yeah. It’s weird. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by josephmancuso** [comment]
i have no idea why that release broke 3.4. That is not cool. I really like your fix though. Makes a lot of sense

**Pull request merged**
